### PR TITLE
Port to Python 3

### PR DESCRIPTION
**Pull request by pro-panda**
**Changes to be made in this PR:**
 - Port all `Python` and `C` code in `src/carquinyol`

**Changes already made:**
 - Port all `Python2` code to `python3`

**Note:**
 - Requirements stated in #7 are fulfilled in my [port](https://github.com/Pro-Panda/sugar-toolkit-gtk3/tree/python3-port) of GTK-Toolkit3
 - This is an in-progress PR. Suggestions on in-progress testing are welcome.

### CODE REVIEW

**Comment by quozl** [comment]
Reviewed to f77312b.

**Comment by quozl** [comment]
Reviewed to 637024d.

**Comment by quozl** [comment]
Reviewed to 6ba080f, thanks.

**Comment by Pro-Panda** [comment]
I am able to install the Python 3 version, but the datastore isn't getting instantiated (my guess). [Here](https://gist.github.com/Pro-Panda/19476e47360864a3b952004681f07204) are the logs in `shell.log`. 

`datastore.log` is not formed.

For the sugar-toolkit dependencies, I am using my Python 3 port of `Sugar-Toolkit`

**Comment by Pro-Panda** [comment]
For record purposes, @quozl suggested testing `datastore-service` by running it independently to find the cause of the error. This worked, thanks

I have tested this port and didn't observe any errors as of now (completing the dependency on Sugar Toolkit using my [port](https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/383))

`Sugar-Datastore` currently depends on `python-xapian` whereas the `Python 3` version requres `python3-xapian`. The original dependancy is not mentioned anywhere. Should `python3-xapian` be mentioned ?

While building `Sugar Datastore`, using
```shell
./autogen.sh
make
make install
```
it is installed in `/usr/local/` instead of `/usr/`, where the Python 2 version was installed.
[Here](https://gist.github.com/Pro-Panda/19476e47360864a3b952004681f07204) are the installation logs. Any suggestions on what could be the cause of this inconsistency ?

**Comment by quozl** [comment]
Thanks for the questions.

> Should python3-xapian be mentioned?

No.  `README.md` already lists Xapian bindings as a dependency, and our use of the binding is easily detected; there's an `import xapian`.

For your interest, the resolution of dependencies is handled by people who do distribution packaging.  

At Sugar Labs we are most focused on making sure things work for Debian and Fedora.  Other distributions often use the same techniques as these two distributions, or are very familiar with how to adapt.

So you might ask yourself; why does the Debian package become marked as needing Xapian?

Have a look at [Debian source package search for sugar-datastore](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=sourcenames&keywords=sugar-datastore), then click on _sid_ (the experimental distribution), which will take you to [sugar-datastore for sid](https://packages.debian.org/source/sid/sugar-datastore), then download and unpack the debian.tar.xz file.  This file shows what is added, changed, or deleted, between our source and the Debian package.  In this you will find two interesting files;

* `debian/rules`, a Makefile, which specifies some explicit dependencies, like this;
```
CDBS_DEPENDS_$(pkg) = python-gi, python-dbus, python-xapian, python-sugar3
```
and

* `debian/control`, which specifies how the dependencies are discovered, like this;
```
Package: python-carquinyol
Architecture: any
Depends: ${cdbs:Depends},
 ${misc:Depends},
 ${python:Depends},
 ${shlibs:Depends}
```

I'm not exactly sure how this bit works, but my guess is that `${cdbs:Depends}` is expanded from what is defined in the `debian/control` file, and the `${python:Depends}` is expanded from anything found by a search of the `import` statements. 

You can also type `sudo apt source sugar-datastore` to download and unpack the source package from your distribution.  Just depends on whether you want to work in a web browser or a command shell.

> it is installed in /usr/local/ instead of /usr/ [... w]hat could be the cause of this inconsistency?

This is normal.  GNU standards for software so that system files are not clobbered.  It would be a bug if our "make install" installed in `/usr` without being asked to do so.  Look up the DESTDIR keyword for details.

For your interest, the Debian and Fedora packaging processes change DESTDIR to `/usr`, and they take responsibility for not clobbering files unless they intend to do so.

**Comment by quozl** [comment]
Reviewed to 4c2ab5c.

**Comment by Pro-Panda** [comment]
current status; C extension fixed, but journal doesn't get updated

steps to reproduce:
 - open sugar
 - open logs, then stop the activity (Keep error is raised, click on stop anyway)
 - No journal entry for logs
 - open cowBulls, then stop (No keep error raised)
 - No journal entry again

The entries are getting stored in `~/.sugar/default/datastore` as they should
 Logs [here](https://gist.github.com/Pro-Panda/49adae2f6a8a976fced8e84700bd1fc2)

I couldn't find the issue in the logs. Kindly suggest on what should I do
@quozl @walterbender @iamutkarshtiwari @divyanshu-rawat

**Comment by quozl** [comment]
One of the errors suggests the datastore process has prematurely terminated in response to a transaction.  

> `DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`

A termination of the datastore will give the results you observe.  Please reproduce to that point, then check that the datastore process has indeed terminated, and if so repeat with gdb attached to establish a backtrace at the point of failure.

You might re-use or write a test client for the datastore rather than diving right into the complexity of Sugar and activities.

You should also use dbus-monitor to track the activity.

Hope that helps.

**Comment by Pro-Panda** [comment]
@quozl, I _think_ [this](https://gist.github.com/Pro-Panda/49adae2f6a8a976fced8e84700bd1fc2#file-shell-log-L398) is the cause. But I can't see how to fix this

**Comment by quozl** [comment]
> `Datastore find failed org.freedesktop.DBus.Error.ServiceUnknown: The name :1.14 was not provided by any .service files`

What line of code emits that message?

[This](https://gist.github.com/Pro-Panda/49adae2f6a8a976fced8e84700bd1fc2#file-org-laptop-log-1-log-L49) is the best indication of a problem.  I suggest writing a GLib MainLoop test program to call sugar3 datastore directly.

**Comment by quozl** [comment]
Rebased to *master* so as to avoid the merge commit.  Reviewed to 8c34d67.

**Comment by quozl** [comment]
Rebased to _master_ after recent commits.  Pushed as branch python3 because @pro-panda has deleted fork.  I've made a new pull request.

**Comment by pro-panda** [comment]
oops. The open PR slipped through my mind when removing the fork

**Pull request closed without merging**
